config/routes.rb
Rails.application.routes.draw do
  
  # Routes for main resources
  resources :addresses
  resources :customers
  resources :orders
  resources :items
  resources :users
  resources :sessions
  resources :item_prices

  # Semi-static page routes
  get 'users/new', to: 'users#new', as: :signup
  get 'user/edit', to: 'users#edit', as: :edit_current_user
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy
  get 'search' => 'home#search', as: :search
  get 'customer_dash' => 'home#customer', as: :customer_dashboard
  get 'cart/:id/add' => 'orders#add_to_cart', as: :add_to_cart
  get 'cart/:id/remove' => 'orders#remove_from_cart', as: :remove_from_cart
  get 'addresses/:id/deactivate' => 'addresses#deactivate', as: :address_deactivate
  get 'addresses/:id/activate' => 'addresses#activate', as: :address_activate
  get 'customers/:id/deactivate' => 'customers#deactivate', as: :customer_deactivate
  get 'customers/:id/activate' => 'customers#activate', as: :customer_activate
  get 'users/:id/deactivate' => 'users#deactivate', as: :user_deactivate
  get 'users/:id/activate' => 'users#activate', as: :user_activate
  get 'items/:id/deactivate' => 'items#deactivate', as: :item_deactivate
  get 'items/:id/activate' => 'items#activate', as: :item_activate
  get 'cart' => 'home#cart', as: :cart
  patch 'order_items/:id/mark_unshipped' => 'order_items#mark_unshipped', as: :mark_unshipped
  patch 'order_items/:id/mark_shipped' => 'order_items#mark_shipped', as: :mark_shipped
  get 'shipper' => 'home#shipper', as: :shipper_dashboard
  get 'baker' => 'home#baker', as: :baker_dashboard
  get 'admin' => 'home#admin', as: :admin_dashboard

  # get 'item_price/new' => 'item_prices#new', as: :new_item_price
  # post 'item_prices', to: 'item_prices#create', as: :item_prices
  
  # Set the root url
  root :to => 'home#home'
  
end

app/views/partials/_add_new_object.html.erb
<!-- Add a button for new instances of object -->
  <%= link_to(eval("new_#{model_name}_path"), class: "waves-effect waves-light btn pulse") do %>
    <strong>Add a New <%= model_name.capitalize %></strong>
  <% end %>

app/views/partials/_flash.html.erb
<% flash.each do |name, msg| %>
  <div data-alert data-options="animation_speed:500, animation:'fadeOut';" class="alert-box <%= flash[:notice] ? "success" : "warning" %>">
    <!-- <a href="#" class="close">&times;</a> -->
    <%= msg %>
  </div>
<% end %>

app/views/partials/_footer.html.erb
<p class="supertiny">&nbsp;</p>

<div id="footer" class="center-align">
  
  <%= link_to 'Home', home_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
  <%= link_to 'About Baking Factory', about_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
  <%= link_to 'Contact Us', contact_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
  <%= link_to 'Privacy Policy', privacy_path %>
  <br />
  <div id="copy">
    Webmaster: <%= mail_to("dgajaraw@andrew.cmu.edu", "Dillan Gajarawala", encode: "javascript") %> 
    &nbsp;&nbsp;&copy 2019
  </div>

</div>

app/views/partials/_form_structure.html.erb
<div class="row">
  <div class="col s9">
    <div class="card">    
      <div class="card-content">
        <span class="card-title"><%= type_of_form %></span><br>
        <%= simple_form_for(object) do |f| %>
          <%= f.error_notification %>
          <div class="row">
            <div class="form-inputs">
              <%= render partial: "#{fields}", locals: { f: f } %>
          </div>
        </div>
      </div>
    </div>
      <div class="row">
        <div class="form-actions col s9">
          <%= f.button :submit %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%= link_to 'Back', :back %>

app/views/partials/_item_list.html.erb
<% unless items.nil? || items.empty? %>
  <% unless item_type.nil?%>
    <h5><%= item_type.capitalize %></h5>
  <% end %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th width="200">Name</th>
        <th width="100">Price</th>
        <th width="100">Units</th>
        <th width="150">&nbsp;</th>
        <th width="100">&nbsp;</th>
      </tr>
    </thead>
    <tbody>
      <% items.each do |item| %>
        <tr>
          <td><%= link_to item.name, item_path(item) %></td>
          <td><%= number_to_currency item.current_price %></td>
          <td><%= item.units_per_item %> <%= item.category == 'bread' ? 'loaf' : item.category %></td>
            <td>
            <% if can? :add_to_cart, Order %>
              <%= link_to(add_to_cart_path(item), class: 'waves-effect waves-light btn') do %>
                &nbsp;Add to <i id="add_to_cart_icon" class="material-icons right white-text">shopping_cart</i>&nbsp;
              <% end %>
            <% end %>
            </td>
            <td>
          <% if logged_in? && current_user.role?(:admin) %> 
            <% if item.active? || item.active.nil? %>
              <%= link_to "Deactivate", item_deactivate_path(item), class: 'waves-effect waves-light btn' %>
            <% else %> 
              <%= link_to "Activate", item_activate_path(item), class: 'waves-effect waves-light btn' %>
            <% end %>
          <% end %>
        </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/partials/_nav_guest.html.erb
<nav id="nav">
  <div class="container">
    <ul class="left hide-on-med-and-down">
      <li><%= link_to 'Items', items_path %></li>
    </ul>
    <ul class="right">
      <li><%= link_to(login_path) do %>
                &nbsp;Login<i id="login-icon" class="material-icons right">fingerprint</i>&nbsp;
              <% end %></li>
    </ul>
    <div class="welcome-text" align="right">Welcome, Guest</div>
  </div>
</nav>

app/views/partials/_nav_shipper.html.erb
<nav id="nav">
  <div class="container">
    <ul class="left hide-on-med-and-down">
      <li><%= link_to 'Order List', shipper_dashboard_path %></li>
      <li><%= link_to 'Items', items_path %></li>
    </ul>
    <ul class="right">
      <li><%= link_to 'Logout', logout_path %></li>
    </ul>
    <div class="welcome-text" align="right">Welcome, <%= current_user.username.capitalize %></div>
  </div>
</nav>

app/views/partials/_object_options.html.erb
<% opt = "#{object.respond_to?(:name) ? object.name : model_name.capitalize }" %>

<div class="form-actions">
    <% if can? :index, eval("#{model_name.titleize}")%>
      <%= link_to(eval("#{model_name.pluralize}_path"), class: 'waves-effect waves-light btn') do %>
        &nbsp;Display All <% model_name.pluralize.capitalize %>
      <% end %>
    <% end %>
    &nbsp;&nbsp;
  
  <% if controller.respond_to?(:update) %>
    <% if can? :update, eval("#{model_name.titleize}") %>
      <% if current_user.role?(:customer) && controller.controller_name == "customers" %>
        <%= link_to(eval("edit_#{model_name}_path(object)"), class: 'waves-effect waves-light btn') do %>
          &nbsp;<%= "Edit My Info" %>
        <% end %>
      <% else %>
        <%= link_to(eval("edit_#{model_name}_path(object)"), class: 'waves-effect waves-light btn') do %>
            &nbsp;<%= "Edit #{opt}" %>
        <% end %>
      <% end %>
    <% end %>
    &nbsp;&nbsp;
    <% end %>

  <% if controller.respond_to?(:deactivate) || controller.respond_to?(:activate) %>
     <% if logged_in? && current_user.role?(:admin) %> 
        <% if object.active? %>
          <%= link_to(eval("#{model_name}_deactivate_path(object)"), class: 'waves-effect waves-light btn') do %>
          &nbsp;<%= "Deactivate #{opt}" %>
          <% end %>
        <% else %> 
          <%= link_to(eval("#{model_name}_activate_path(object)"), class: 'waves-effect waves-light btn') do %>
          &nbsp;<%= "Activate #{opt}" %>
          <% end %>
        <% end %>
      <% end %>
  <% end %> 
  &nbsp;&nbsp;
  
  <% if controller.respond_to?(:destroy) %>
    <% if can? :destroy, eval("#{model_name.titleize}")%>
      <%= link_to(eval("#{model_name}_path(object)"), method: 'delete', data: {confirm: "Are you sure you want to permanently delete #{opt}"}, class: 'waves-effect waves-light btn btn-alert') do %>
          &nbsp;<%= "Delete #{opt}" %>
      <% end %>
    <% end %>
  <% end %>

</div>

app/views/partials/_order_item_list.html.erb
<table class="table table-striped centered">
  <thead>
    <tr>
      <th width="100">Quantity</th>
      <th width="300">Item</th>
      <th width="100">Unit Price</th>
      <th width="100">Subtotal</th>
      <% if controller.controller_name == 'home' %>
        <th>Shipped?</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% order_items.each do |oi| %>
      <tr>
        <td align="center"><%= oi.quantity %></td>
        <td><%= link_to oi.item.name, item_path(oi.item) %></td>
        <td align="center"><%= number_to_currency oi.item.price_on_date(oi.order.date) %></td>
        <td align="right"><%= number_to_currency oi.subtotal(oi.order.date) %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
        <% if controller.controller_name == 'home' %>
          <td>
            <% if oi.shipped_on.nil? %>
              <% if oi.order.order_items.unshipped.size == 1 %>
                <%= link_to(eval("mark_shipped_path(oi)"), method: 'patch', data: {confirm: "Are you sure you want to totally ship this order? You cannot go back from this."}, class: 'material-icons') do %>
          &nbsp;check_box_outline_blank
                <% end %>
              <% else %>
                <%= link_to 'check_box_outline_blank', mark_shipped_path(oi), class: 'material-icons', method: 'patch' %>
              <% end %>
            <% else %>
              <%= link_to 'check', mark_unshipped_path(oi), class: 'material-icons', method: 'patch' %>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br><br>

app/views/partials/_previous_orders.html.erb
<% unless @previous_orders.empty? %>
  <div class="card hoverable">
    <div class="card-content">
      <span class="card-title">Order History</span>
    <table>
      <thead>
        <tr>
          <th width="120">Date</th>
          <th width="100">Amount</th>
        </tr>
      </thead>
      <tbody>
      <% @previous_orders.each do |order| %>
        <tr>
          <td><%= link_to order.date.strftime('%B %e, %Y'), order_path(order) %></td>
          <td><%= number_to_currency order.grand_total %></td>
        </tr>
      <% end %>
    </table>
  </div>
  </div>
<% end %>

app/views/partials/_price_history.html.erb
<br><br>
<% unless @previous_prices.empty? %>
  <div class="card hoverable">
    <div class="card-content">
      <span class="card-title">Price History</span>
    <table>
      <thead>
        <tr>
          <th width="120">Start Date</th>
          <th width="120">End Date</th>
          <th width="100">Price</th>
        </tr>
      </thead>
      <tbody>
      <% @previous_prices.each do |pp| %>
        <tr>
          <td><%= pp.start_date.strftime('%B %e, %Y') %></td>
        <td><% if pp.end_date.nil? %><i>Current Price<i><% else %><%= pp.end_date.strftime('%m/%d/%y') %><% end %></td>
          <td><%= number_to_currency pp.price %></td>
        </tr>
      <% end %>
    </table>
       </div>
    <% if can? :new, ItemPrice %>
      <div class="card-action">
        <%= link_to "Add a new price", new_item_price_path(item_id: @item.id), id: "add-new-price" %>
      </div>
    <% end %>
  </div>
  </div>
<% end %>

app/views/partials/_search_with_title.html.erb
<br><div class="row">
    <div class="col s7">
      <h4><%= title %></h4>
    </div>
    <div class="col s5">

          <%= form_with url: search_path, method: :get, class: "form-inline", id: "search" do %>
              <%= text_field_tag 'query', '', placeholder: "Search ..." %>
              <!-- submitting via js (press enter) so not using... -->
              <%# submit_tag('Find') %>
            
          <% end %>

    </div>
  </div>

app/views/partials/_search_without_title.html.erb
<% if current_user.role?(:admin) %>
    <%= form_with url: search_path, method: :get, class: "form-inline", id: "search" do %>
                <%= text_field_tag 'query', '', placeholder: "Search Items and Customers..." %>
                <!-- submitting via js (press enter) so not using... -->
                <%# submit_tag('Find') %>
                
            <% end %>
<% elsif current_user.role?(:customer) %>
    <%= form_with url: search_path, method: :get, class: "form-inline", id: "search" do %>
                <%= text_field_tag 'query', '', placeholder: "Search Items..." %>
                <!-- submitting via js (press enter) so not using... -->
                <%# submit_tag('Find') %>
                
            <% end %>
<% end %>

app/views/partials/_similar_items.html.erb
<% unless @similar_items.empty? %><br><br>
  <div class="card hoverable">
    <div class="card-content">
      <span class="card-title">Similar Items</span>
      <table>
        <thead>
          <tr>
            <th width="120">Name</th>
            <th width="100">Price</th>
          </tr>
        </thead>
        <tbody>
          <% @similar_items.each do |item| %>
            <tr>
              <td><%= link_to item.name, item_path(item) %></td>
              <td><%= number_to_currency item.current_price %></td>
            </tr>
          <% end %>
      </table>
    </div>
  </div>
<% end %>