config/routes.rb
Rails.application.routes.draw do
  
  # Routes for main resources
  resources :addresses
  resources :customers
  resources :orders
  resources :items
  resources :users
  resources :sessions
  resources :item_prices

  # Semi-static page routes
  get 'users/new', to: 'users#new', as: :signup
  get 'user/edit', to: 'users#edit', as: :edit_current_user
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy
  get 'search' => 'home#search', as: :search
  get 'customer_dash' => 'home#customer', as: :customer_dashboard
  get 'cart/:id/add' => 'orders#add_to_cart', as: :add_to_cart
  get 'cart/:id/remove' => 'orders#remove_from_cart', as: :remove_from_cart
  get 'addresses/:id/deactivate' => 'addresses#deactivate', as: :address_deactivate
  get 'addresses/:id/activate' => 'addresses#activate', as: :address_activate
  get 'customers/:id/deactivate' => 'customers#deactivate', as: :customer_deactivate
  get 'customers/:id/activate' => 'customers#activate', as: :customer_activate
  get 'users/:id/deactivate' => 'users#deactivate', as: :user_deactivate
  get 'users/:id/activate' => 'users#activate', as: :user_activate
  get 'items/:id/deactivate' => 'items#deactivate', as: :item_deactivate
  get 'items/:id/activate' => 'items#activate', as: :item_activate
  get 'cart' => 'home#cart', as: :cart
  patch 'order_items/:id/mark_unshipped' => 'order_items#mark_unshipped', as: :mark_unshipped
  patch 'order_items/:id/mark_shipped' => 'order_items#mark_shipped', as: :mark_shipped
  get 'shipper' => 'home#shipper', as: :shipper_dashboard
  get 'baker' => 'home#baker', as: :baker_dashboard
  get 'admin' => 'home#admin', as: :admin_dashboard

  # get 'item_price/new' => 'item_prices#new', as: :new_item_price
  # post 'item_prices', to: 'item_prices#create', as: :item_prices
  
  # Set the root url
  root :to => 'home#home'
  
end

app/models/user.rb
class User < ApplicationRecord
  # get modules to help with some functionality
  include AppHelpers::Deletions
  include AppHelpers::Activeable::InstanceMethods
  extend AppHelpers::Activeable::ClassMethods

  # Use built-in rails support for password protection
  has_secure_password

  # Relationships
  has_one :customer

  # Scopes
  scope :by_role,      -> { order(:role) }
  scope :alphabetical, -> { order(:username) }
  scope :employees,    -> { where.not(role: 'customer') }

  # Validations
  validates :username, presence: true, uniqueness: { case_sensitive: false}
  validates :role, inclusion: { in: %w[admin baker shipper customer], message: "is not a recognized role in system" }
  validates_presence_of :password, on: :create 
  validates_presence_of :password_confirmation, on: :create 
  validates_confirmation_of :password, on: :create, message: "does not match"
  validates_length_of :password, minimum: 4, message: "must be at least 4 characters long", allow_blank: true

  # For use in authorizing with CanCan
  ROLES = [['Administrator', :admin],['Baker', :baker],['Shipper', :shipper],['Customer',:customer]]

  def role?(authorized_role)
    return false if role.nil?
    role.downcase.to_sym == authorized_role
  end

  # Callbacks
  before_destroy :cannot_destroy_object
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :current_user, only: [:show, :edit]
    before_action :set_user, only: [:show, :edit, :update, :deactivate, :activate]
    before_action :check_login
    before_action :get_num_items
    authorize_resource

    def index
      @non_customer_users = User.all.employees.paginate(:page => params[:page]).per_page(10)
    end

    def new
        @user = User.new
    end

    def edit
    end

    def create
        @user = User.new(user_params)
        if @user.save
          redirect_to users_url, :notice => 'User was successfully created.'
        else
          render :action => "new"
        end
      end
    
      # PATCH/PUT /genres/1
      # PATCH/PUT /genres/1.json
    def update
      if @user.update_attributes(user_params)
        redirect_to users_url, :notice => 'User was successfully updated.'
      else
        render :action => "edit"
      end
    end

    def activate
      @user.make_active
      redirect_to users_url, notice: "#{@user.username} was activated"
    end
    
    def deactivate
      @user.make_inactive
      redirect_to users_url, notice: "#{@user.username} was deactivated"
    end

    private

    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :role, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_fields.html.erb
<%= f.input :username, label_html: { class: 'active' } %>
<% if current_user.role?(:admin) %>
  <%= f.input :role, collection: User::ROLES, include_blank: true %>
<% end %>
<%= f.input :password, label_html: { class: 'active' } %>
<%= f.input :password_confirmation, label_html: { class: 'active' } %>
<%= f.input :active %>

app/views/users/_user_list.html.erb
<% if @non_customer_users.empty? %>
  <h4>No users at this time.</h4>
<% else %>
  <h4>Employees</h4>
  <table class="table table-striped">
    <thead>
      <tr>
        <th width="225">Username</th>
        <th width="125">Role</th>
        <th width="200">Active</th>
      </tr>
    </thead>
    <tbody>
      <% @non_customer_users.each do |user| %>
        <tr>
          <td><%= user.username %></td>
          <td><%= user.role.capitalize %></td>
          <td><%= (user.active || user.active.nil?) ? 'Yes' : 'No'  %></td>
          <td>
          <%= link_to(edit_user_path(user), class: 'waves-effect waves-light btn-floating hoverable z-depth 5') do %>
            <i class="material-icons black-text">edit</i>
          <% end %>
        </td>
        <td>
          <% if logged_in? && current_user.role?(:admin) %> 
            <% if user.active? || user.active.nil? %>
              <%= link_to "Deactivate", user_deactivate_path(user), class: 'waves-effect waves-light btn' %>
            <% else %> 
              <%= link_to "Activate", user_activate_path(user), class: 'waves-effect waves-light btn' %>
            <% end %>
          <% end %>
        </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<%= will_paginate @non_customer_users, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>  
<% end %>
<p>&nbsp;</p>

app/views/users/edit.html.erb
<%= render partial: "partials/form_structure", locals: {object: @user, 
                                                        type_of_form: "Edit User",
                                                        fields: "fields"} %>

app/views/users/index.html.erb
<%= render partial: "partials/index_structure", locals: {model_name: "user", 
                                                         primary: "user_list", 
                                                         secondary: nil,
                                                         sidebar: nil} %>

app/views/users/new.html.erb
<%= render partial: "partials/form_structure", locals: {object: @user, 
                                                        type_of_form: "Create a New User",
                                                        fields: "fields"} %>