config/routes.rb
Rails.application.routes.draw do
  
  # Routes for main resources
  resources :addresses
  resources :customers
  resources :orders
  resources :items
  resources :users
  resources :sessions
  resources :item_prices

  # Semi-static page routes
  get 'users/new', to: 'users#new', as: :signup
  get 'user/edit', to: 'users#edit', as: :edit_current_user
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy
  get 'search' => 'home#search', as: :search
  get 'customer_dash' => 'home#customer', as: :customer_dashboard
  get 'cart/:id/add' => 'orders#add_to_cart', as: :add_to_cart
  get 'cart/:id/remove' => 'orders#remove_from_cart', as: :remove_from_cart
  get 'addresses/:id/deactivate' => 'addresses#deactivate', as: :address_deactivate
  get 'addresses/:id/activate' => 'addresses#activate', as: :address_activate
  get 'customers/:id/deactivate' => 'customers#deactivate', as: :customer_deactivate
  get 'customers/:id/activate' => 'customers#activate', as: :customer_activate
  get 'users/:id/deactivate' => 'users#deactivate', as: :user_deactivate
  get 'users/:id/activate' => 'users#activate', as: :user_activate
  get 'items/:id/deactivate' => 'items#deactivate', as: :item_deactivate
  get 'items/:id/activate' => 'items#activate', as: :item_activate
  get 'cart' => 'home#cart', as: :cart
  patch 'order_items/:id/mark_unshipped' => 'order_items#mark_unshipped', as: :mark_unshipped
  patch 'order_items/:id/mark_shipped' => 'order_items#mark_shipped', as: :mark_shipped
  get 'shipper' => 'home#shipper', as: :shipper_dashboard
  get 'baker' => 'home#baker', as: :baker_dashboard
  get 'admin' => 'home#admin', as: :admin_dashboard

  # get 'item_price/new' => 'item_prices#new', as: :new_item_price
  # post 'item_prices', to: 'item_prices#create', as: :item_prices
  
  # Set the root url
  root :to => 'home#home'
  
end

app/models/order.rb
class Order < ApplicationRecord
  # get module to help with some functionality
  include AppHelpers::Validations
  include AppHelpers::Deletions
  include AppHelpers::Shipping
  require 'base64'

  # Relationships
  belongs_to :customer
  belongs_to :address
  has_many :order_items
  has_many :items, through: :order_items

  # Virtual attributes (non-saved)
  attr_accessor :credit_card_number
  attr_accessor :expiration_year
  attr_accessor :expiration_month

  # Scopes
  scope :chronological, -> { order(date: :desc) }
  scope :paid,          -> { where.not(payment_receipt: nil) }
  scope :for_customer,  ->(customer_id) { where(customer_id: customer_id) }

  # Class methods
  def self.not_shipped
    # joins(:order_items).where("order_items.shipped_on IS NULL").to_a.uniq
    joins(:order_items).where("order_items.shipped_on IS NULL").distinct

  end

  # Other methods
  def unshipped_items
    self.order_items.unshipped
  end

  # Validations
  # validates_date :date
  # validates_numericality_of :grand_total, greater_than_or_equal_to: 0, allow_blank: true
  validates_presence_of :customer_id, :address_id
  validate :customer_is_active_in_system
  validate :address_is_active_in_system
  validate :credit_card_number_is_valid
  validate :expiration_date_is_valid

  # Other methods
  def is_editable?
    !self.order_items.unshipped.empty?
  end

  def pay
    return false unless self.payment_receipt.nil?
    generate_payment_receipt
    self.save!
    self.payment_receipt
  end

  def total_weight
    weight = self.order_items.inject(0){|sum, oi| sum += oi.item.weight * oi.quantity}
  end

  def shipping_costs
    calculate_shipping_costs(self.total_weight, base=2.00)
  end

  def credit_card_type
    credit_card.type.nil? ? "N/A" : credit_card.type.name
  end

  # Callbacks
  before_destroy do
    check_if_any_order_items_shipped
    if errors.present?
      @destroyable = false
      throw(:abort)
    end
    remove_order_items
  end

  private
  def customer_is_active_in_system
    is_active_in_system(:customer)
  end

  def address_is_active_in_system
    is_active_in_system(:address)
  end

  def generate_payment_receipt
    self.payment_receipt = Base64.encode64("order: #{self.id}; amount_paid: #{self.grand_total}; received: #{self.date}; card: #{self.credit_card_type} ****#{self.credit_card_number[-4..-1]}; billing zip: #{self.customer.billing_address.zip}")
  end

  def credit_card
    CreditCard.new(self.credit_card_number, self.expiration_year, self.expiration_month)
  end

  def credit_card_number_is_valid
    return false if self.expiration_year.nil? || self.expiration_month.nil?
    if self.credit_card_number.nil? || credit_card.type.nil?
      errors.add(:credit_card_number, "is not valid")
      return false
    end
    true
  end

  def expiration_date_is_valid
    return false if self.credit_card_number.nil? 
    if self.expiration_year.nil? || self.expiration_month.nil? || credit_card.expired?
      errors.add(:expiration_year, "is expired")
      return false
    end
    true
  end

  def check_if_any_order_items_shipped
    unless self.order_items.shipped.empty?
      errors.add(:base, "This order has already been partially shipped and therefore cannot be deleted.")
    end
  end

  def remove_order_items
    self.order_items.each{ |oi| oi.destroy }
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include AppHelpers::Cart
  include AppHelpers::Shipping

  before_action :set_order, only: [:show, :destroy]
  before_action :set_item, only: [:add_to_cart, :remove_from_cart]
  before_action :get_num_items
  authorize_resource
  
  def index
    if current_user.role?(:admin)
      @pending_orders = Order.not_shipped.chronological.paginate(:page => params[:page]).per_page(10)
      @past_orders = Order.where(id: (Order.all - @pending_orders)).chronological.paginate(:page => params[:page]).per_page(10)
    elsif current_user.role?(:customer)
      @pending_orders = Order.for_customer(current_user.customer.id).not_shipped.chronological.paginate(:page => params[:page]).per_page(10)
      @past_orders = Order.where(id: (Order.for_customer(current_user.customer.id) - @pending_orders)).chronological.paginate(:page => params[:page]).per_page(10)
    end
  end

  def show
    @previous_orders = @order.customer.orders.chronological.to_a - [@order]
    @order_items = @order.order_items
  end

  def new
    @order = Order.new
    @order_subtotal = calculate_cart_items_cost
    @shipping_costs = calculate_cart_shipping
    @cart_items = get_list_of_items_in_cart
  end

  def create
    @order_subtotal = calculate_cart_items_cost
    @shipping_costs = calculate_cart_shipping
    @order = Order.new(order_params)
    @order.date = Date.current
    @order.customer_id = current_user.customer.id
    @order.credit_card_number = @order.credit_card_number
    @order.expiration_year = @order.expiration_year.to_i
    @order.expiration_month = @order.expiration_month.to_i
    @order.grand_total = @order_subtotal + @shipping_costs
    if @order.save
      @order.pay
      save_each_item_in_cart(@order)
      clear_cart
      redirect_to @order, notice: "Thank you for ordering from the Baking Factory."
    else
      render action: 'new'
    end
  end

  def add_to_cart
    add_item_to_cart(@item.id.to_s)
    redirect_to items_url, notice: "#{@item.name} has been added to your cart"
  end

  def remove_from_cart
    remove_item_from_cart(@item.id.to_s)
    redirect_to cart_path, notice: "#{@item.name} has been removed from your cart"
  end

  private
  def set_order
    @order = Order.find(params[:id])
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def order_params
    if logged_in? && current_user.role?(:admin)
      params.require(:order).permit(:address_id, :customer_id, :grand_total, :credit_card_number, :expiration_year, :expiration_month)
    elsif logged_in? && current_user.role?(:customer)
      params.require(:order).permit(:address_id, :credit_card_number, :expiration_year, :expiration_month)
    end
  end

end

app/views/orders/_all_orders.html.erb
<% if @all_orders.empty? %>
  <p><em>There are no orders at this time.</em></p>
<% else %>
  <% if logged_in? && current_user.role?(:admin) %>
    <%= render :partial => "order_list", locals: {status: 'All', orders: @all_orders} %>  
  <% elsif logged_in? && current_user.role?(:customer) %>
    <%= render :partial => "order_list", locals: {status: 'Your', orders: @all_orders} %>
  <% end %>  
<% end %>
<br />

app/views/orders/_fields.html.erb
    <% if logged_in? && current_user.role?(:admin) %>
        <%= f.input :customer_id, collection: Customer.active.alphabetical, include_blank: true, label_html: {class: "active"} %>
    <% end %>
    <%= f.input :address_id, collection: get_address_options(current_user), include_blank: true, label_html: {class: "active"} %>
    <% if logged_in? && current_user.role?(:admin) %>
        <%= f.input :grand_total, as: :string, label_html: {class: "active"} %>
    <% end %>
    <%= f.input :credit_card_number, as: :string, label_html: {class: "active"} %>
    <%= f.input :expiration_month, as: :string, label_html: {class: "active"} %>
    <%= f.input :expiration_year, as: :string, label_html: {class: "active"} %>

app/views/orders/_form.html.erb
<div class="row">
  <div class="col s8">
    <div class="card">    
      <div class="card-content">
        <span class="card-title">Complete Your Order</span><br>
        <%= simple_form_for(@order) do |f| %>
          <%= f.error_notification %>
          <div class="row">
            <div class="form-inputs">
              <%= render partial: "fields", locals: { f: f } %>
          </div>
        </div>
        </br></br>Order Subtotal: <%= number_to_currency @order_subtotal %>
        </br></br>Shipping Costs: <%= number_to_currency @shipping_costs %>
        </br></br>Grand Total: <%= number_to_currency (@order_subtotal+@shipping_costs)%>
      </div>
    </div>
      <div class="row">
        <div class="form-actions col s9">
          <%= f.button :submit, label: "Place Order" %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col s4">
    <div class="card hoverable">    
      <div class="card-content">
        <span class="card-title">Your Cart</span>
          <table class="table table-striped">
          <thead>
            <tr>
              <th width="400">Item</th>
              <th width="20">Quantity</th>
              <th width="225">Subtotal</th>
              <th width="20"></th>
            </tr>
          </thead>
          <tbody>
            <% @cart_items.each do |ci| %>
              <tr>
                <td><%= link_to ci.item.name, item_path(ci.item) %></td>
                <td><%= ci.quantity %></td>
                <td><%= number_to_currency ci.subtotal %></td>
                <td>
                  <%= link_to(remove_from_cart_path(ci.item), class: 'button tiny radius') do %>
                      &nbsp;<i class="material-icons red-text">close</i>&nbsp;
                  <% end %>
                  </td>
              </tr>
            <% end %>
          </tbody>
          </table>
      </div>
    </div>
  </div>
</div>
<%= link_to 'Back', cart_path %>

app/views/orders/_order_details.html.erb
<h3>Order Details</h3>

<p>
  <b>Date</b>: <%= @order.date.strftime('%B %e, %Y') %>
</p>

<p>
  <b>Customer</b>: <%= link_to @order.customer.name, customer_path(@order.customer) %>
</p>

<p>
  <b>Recipient</b>: <%= link_to @order.address.recipient, address_path(@order.address) %>
</p>


<p>
  <b>Total Cost</b>: <%= number_to_currency @order.grand_total %>
</p>


<p>
  <em>Thanks for being a Baking Factory customer since <%= @order.customer.created_at.year %>.</em>
</p>

app/views/orders/_order_item_list.html.erb
<ul class="collapsible">
  <li>
      <div class="collapsible-header" align="center"><h6 class="center-align">Items</h6><i class="material-icons" align="right">arrow_downward</i></div>
      <div class="collapsible-body"><span><%= render partial: 'partials/order_item_list', locals: {order_items: @order_items} %></span></div>
  </li>
</ul><br><br>

app/views/orders/_order_list.html.erb
  <h4><%= state %> Orders</h4>
  <% if orders.empty? %>
    <% if current_user.role?(:admin) %>
      There are no <%= state.downcase %> orders at this time.
    <% elsif current_user.role?(:customer) %>
      You have no <%= state.downcase %> orders at this time.
    <% end %>
  <% else %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th width="100">Date</th>
        <th width="225">Customer</th>
        <th width="225">Recipient</th>
        <th width="100">Cost</th>
      </tr>
    </thead>
    <tbody>
      <% orders.each do |order| %>
        <tr>
          <td><%= link_to order.date.strftime('%m/%d/%y'), order_path(order) %></td>
          <td><%= link_to order.customer.name, customer_path(order.customer) %></td>
          <td><%= link_to order.address.recipient, address_path(order.address) %></td>
          <td><%= number_to_currency order.grand_total %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<%= will_paginate orders, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next" %>  
<% end %>

app/views/orders/_tabbed_orders.html.erb
<div id="tabbed">
  <tabs>

    <tab name="pending orders" v-bind:selected="true">
      <%= render :partial => "order_list", locals: {orders: @pending_orders, state: 'Pending'} %>
    </tab>

    <tab name="past orders">
      <%= render :partial => "order_list", locals: {orders: @past_orders, state: 'Past'} %>
    </tab>

  </tabs>
</div>

app/views/orders/index.html.erb
<%= render partial: "partials/index_structure", locals: {model_name: "order", 
                                                         primary: "tabbed_orders", 
                                                         secondary: nil,
                                                         sidebar: nil} %>

app/views/orders/new.html.erb
<% if logged_in? && current_user.role?(:admin) %>
    <%= render partial: "partials/form_structure", locals: {object: @order, 
                                                        type_of_form: "Place an Order with the Baking Factory",
                                                        fields: "fields"} %>
<% elsif logged_in? && current_user.role?(:customer) %>
    <%= render partial: "form" %>

<% end %>

app/views/orders/show.html.erb
<%= render partial: "partials/structure1", locals: {primary: "order_details", 
                                                    secondary: "order_item_list", sidebar: "partials/previous_orders"}%>

<%= render partial: "partials/object_options", locals: {model_name: "order", object: @order}  %>