config/routes.rb
Rails.application.routes.draw do
  
  # Routes for main resources
  resources :addresses
  resources :customers
  resources :orders
  resources :items
  resources :users
  resources :sessions
  resources :item_prices

  # Semi-static page routes
  get 'users/new', to: 'users#new', as: :signup
  get 'user/edit', to: 'users#edit', as: :edit_current_user
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy
  get 'search' => 'home#search', as: :search
  get 'customer_dash' => 'home#customer', as: :customer_dashboard
  get 'cart/:id/add' => 'orders#add_to_cart', as: :add_to_cart
  get 'cart/:id/remove' => 'orders#remove_from_cart', as: :remove_from_cart
  get 'addresses/:id/deactivate' => 'addresses#deactivate', as: :address_deactivate
  get 'addresses/:id/activate' => 'addresses#activate', as: :address_activate
  get 'customers/:id/deactivate' => 'customers#deactivate', as: :customer_deactivate
  get 'customers/:id/activate' => 'customers#activate', as: :customer_activate
  get 'users/:id/deactivate' => 'users#deactivate', as: :user_deactivate
  get 'users/:id/activate' => 'users#activate', as: :user_activate
  get 'items/:id/deactivate' => 'items#deactivate', as: :item_deactivate
  get 'items/:id/activate' => 'items#activate', as: :item_activate
  get 'cart' => 'home#cart', as: :cart
  patch 'order_items/:id/mark_unshipped' => 'order_items#mark_unshipped', as: :mark_unshipped
  patch 'order_items/:id/mark_shipped' => 'order_items#mark_shipped', as: :mark_shipped
  get 'shipper' => 'home#shipper', as: :shipper_dashboard
  get 'baker' => 'home#baker', as: :baker_dashboard
  get 'admin' => 'home#admin', as: :admin_dashboard

  # get 'item_price/new' => 'item_prices#new', as: :new_item_price
  # post 'item_prices', to: 'item_prices#create', as: :item_prices
  
  # Set the root url
  root :to => 'home#home'
  
end

app/models/item.rb
class Item < ApplicationRecord
  # get modules to help with some functionality
  mount_uploader :picture, PictureUploader
  include AppHelpers::Validations
  include AppHelpers::Deletions
  include AppHelpers::Activeable::InstanceMethods
  extend AppHelpers::Activeable::ClassMethods

  # List of allowable categories
  CATEGORIES = [['Bread','bread'],['Muffins','muffins'],['Pastries','pastries']]

  # Relationships
  has_many :order_items
  has_many :item_prices
  has_many :orders, through: :order_items

  # Scopes
  scope :alphabetical, -> { order(:name) }
  scope :active,       -> { where(active: true) }
  scope :inactive,     -> { where(active: false) }
  scope :for_category, ->(category) { where(category: category) }
  scope :search, ->(term) { where('name LIKE ?', "%#{term}%") }
  
  # Validations
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates_numericality_of :units_per_item, only_integer: true, greater_than: 0
  validates_numericality_of :weight, greater_than: 0
  validates_inclusion_of :category, in: CATEGORIES.map{|key, value| value}, message: "is not an option"
  # validates_inclusion_of :category, in: CATEGORIES.to_h.values, message: "is not an option"

  # Other methods
  def current_price
    curr = self.item_prices.current.first
    if curr.nil?
      return nil
    else
      return curr.price
    end
  end

  def price_on_date(date)
    data = self.item_prices.for_date(date).first
    if data.nil?
      return nil
    else
      return data.price
    end
  end

  # Callbacks
  before_destroy do 
    check_if_ever_associated_with_an_order
    if errors.present?
      @destroyable = false
      throw(:abort)
    else
      remove_unshipped_and_unpaid_order_items
    end
  end
  after_destroy :remove_unshipped_and_unpaid_order_items
  after_rollback :convert_to_inactive


  private
  def check_if_ever_associated_with_an_order
    unless self.order_items.shipped.empty?
      errors.add(:base, "This item cannot be deleted because it has been part of a shipped order, but its status has been set to inactive.")
    end
  end

  def convert_to_inactive
    if !@destroyable.nil? && @destroyable == false
      remove_unshipped_and_unpaid_order_items
      make_inactive
    end
    @destroyable = nil
  end

  def remove_unshipped_and_unpaid_order_items
    self.order_items.unshipped.each{|oi| oi.destroy if oi.order.payment_receipt.nil?}
  end


end

app/controllers/items_controller.rb
  class ItemsController < ApplicationController
    include AppHelpers::Cart

  before_action :check_login, except: [:index, :show]
  before_action :set_item, except: [:index, :new, :create]
  before_action :get_num_items
  authorize_resource
  
  def index
    # get info on active items for the big three...
    @breads = Item.active.for_category('bread').alphabetical.paginate(:page => params[:page]).per_page(10)
    @muffins = Item.active.for_category('muffins').alphabetical.paginate(:page => params[:page]).per_page(10)
    @pastries = Item.active.for_category('pastries').alphabetical.paginate(:page => params[:page]).per_page(10)
    # get a list of any inactive items for sidebar
    @inactive_items = Item.inactive.alphabetical.paginate(:page => params[:page]).per_page(10)
  end

  def show
    if logged_in? && current_user.role?(:admin)
      # admin gets a price history in the sidebar
      @previous_prices = @item.item_prices.chronological.to_a
    end
    # everyone sees similar items in the sidebar
    @similar_items = Item.active.for_category(@item.category).alphabetical.to_a - [@item]
  end

  def new
    @item = Item.new
  end

  def edit
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to @item, notice: "#{@item.name} was added to the system."
    else
      render action: 'new'
    end
  end

  def update
    if @item.update(item_params)
      redirect_to @item, notice: "#{@item.name} was revised in the system."
    else
      render action: 'edit'
    end
  end

  def destroy
    @item.destroy
    if !@item.nil? && !@item.active?
      redirect_to items_url, notice: "#{@item.name} was made inactive, because it cannot be deleted."
    else
      redirect_to items_url, notice: "#{@item.name} was removed from the system."
    end
  end

  def activate
    @item.make_active
    redirect_to items_path, notice: "#{@item.name} was activated"
  end

  def deactivate
    @item.make_inactive
    redirect_to items_path, notice: "#{@item.name} was deactivated"
  end

  private
  def set_item
    @item = Item.find(params[:id])
  end


  def item_params
    params.require(:item).permit(:name, :description, :picture, :category, :units_per_item, :weight, :active)
  end

end

app/views/items/_fields.html.erb
<%= f.input :name, as: :string, label_html: {class: "active"}%>
<%= f.input :description, label_html: {class: "active"}%>
<%= f.input :category, collection: Item::CATEGORIES, include_blank: true, label_html: {class: "active"}%>
<%= f.input :units_per_item, as: :integer, label_html: {class: "active"}%>
<%= f.input :weight, as: :float, label_html: {class: "active"}%>
<%= f.input :picture, as: :file, label_html: {class: "active"}, label: "Choose file for Picture"%>
<%= f.input :active %>

app/views/items/_inactive_items.html.erb
<% unless @inactive_items.nil? || @inactive_items.empty? %>
  <h5>Inactive Items</h5>
  <%= render partial: "item_list", locals: {items: @inactive_items, item_type: nil}%>
  <% end %>
  <% if @inactive_items.nil? || @inactive_items.empty? %>
  <i>There are no inactive items at this time.</i><br><br>
  <% end %>

app/views/items/_item_details.html.erb
<h3><%= @item.name %></h3><br>

<% if @item.picture_url.nil? %>
<p><%= image_tag 'nopic.jpg', class: "item-image" %><p>
<% else %>
<%= image_tag @item.picture_url, class: "show-item-image" %>
<% end %>

<p>
  <b>Description</b>:<br> <%= @item.description %>
</p>

<p>
  <b>Category</b>:<br> <%= @item.category.titleize %>
</p>

<p>
  <b>Units per Item</b>:<br> <%= @item.units_per_item %>
</p>

<p>
  <b>Weight</b>:<br> <%= @item.weight %> lbs
</p>

<p>
  <b>Price</b>:<br> <%= number_to_currency @item.current_price %>
</p>

<% if logged_in? && current_user.role?(:admin) %>
    <p>
    <b>Active</b>:<br> <%= @item.active ? 'Yes' : 'No' %>
    </p>
<% end %>

  <% if can? :add_to_cart, Order %>
  <% if current_user.role?(:customer) %>
    <%= link_to "Add to Cart", add_to_cart_path(@item), class: 'waves-effect waves-light btn pulse' %>
  <% else %>
    <%= link_to "Add to Cart", add_to_cart_path(@item), class: 'waves-effect waves-light btn' %>
  <% end %>
<% end %>

app/views/items/_item_grid.html.erb
<% unless items.nil? || items.empty? %>
  <% unless item_type.nil?%>
    <h5 align="center"><%= item_type.capitalize %></h5>
  <% end %>
<div class="row" align="center">
<% items.each do |item| %>
    <div class="col s4">
        <% if item.picture_url.nil? %>
            <p><%= image_tag 'nopic.jpg', class: "item-image" %><p>
        <% else %>
        <p><%= link_to item_path(item) do %>
            <%= image_tag item.picture_url, class: "item-image" %>
            <% end %><p>
        <% end %>
        <%= link_to item.name, item_path(item) %><br>
        Price: <%= number_to_currency item.current_price %> for <%= item.units_per_item %> <%= item.category == 'bread' ? 'loaf' : item.category %><br><br>
        <% if can? :add_to_cart, Order%>
          <%= link_to(add_to_cart_path(item), class: 'waves-effect waves-light btn') do %>
                  &nbsp;Add to<i id="add_to_cart_icon" class="material-icons right white-text">shopping_cart</i>&nbsp;
                <% end %><br><br>
        <% end %>
        <br>
    </div>
<% end %>
</div>
<% end %>

app/views/items/_item_list.html.erb
<% unless items.nil? || items.empty? %>
    <% unless item_type.nil? %>
        <h5><%= item_type.capitalize %></h5>
    <% end %>
    <ul class="collection">
        <% items.each do |item| %>
            <li class="collection-item avatar">
                <% if item.picture_url.nil? %>
                    <%= image_tag 'nopic.jpg', class: "item-image circle"%>
                <% else %>
                    <%= link_to item_path(item) do %>
                        <%= image_tag item.picture_url, class: "circle"%>
                    <% end %>
                <% end %>
                <span class="title"><%= link_to item.name, item_path(item), class: "item-link" %></span>
                <p>Price: <%= number_to_currency item.current_price %> <br>
                    Units: <%= item.units_per_item %> <%= item.category == 'bread' ? 'loaf' : item.category %>
                </p>
                <% if item.active? || item.active.nil? %>
                    <%= link_to "Deactivate", item_deactivate_path(item), class: 'secondary-content waves-effect waves-light btn' %>
                <% else %> 
                    <%= link_to "Activate", item_activate_path(item), class: 'secondary-content waves-effect waves-light btn' %>
                <% end %>
            </li>
        <% end %>
    </ul>
<% end %>

app/views/items/_tabbed_items.html.erb
<div id="tabbed">
  <tabs>

    <tab name="active items" v-bind:selected="true">
        <%= render partial: "item_list", locals: {items: @breads,
                                                      item_type: 'breads'} %>

        <%= render partial: "item_list", locals: {items: @muffins,
                                                      item_type: 'muffins'} %>

        <%= render partial: "item_list", locals: {items: @pastries,
                                                      item_type: 'pastries'} %>
    </tab>

    <tab name="inactive items">
      <%= render :partial => "inactive_items" %>
    </tab>

  </tabs>
</div>

app/views/items/edit.html.erb
<%= render partial: "partials/form_structure", locals: {object: @item, 
                                                        type_of_form: "Edit Item",
                                                        fields: "fields"} %>

app/views/items/index.html.erb
<% if logged_in? && current_user.role?(:customer) %>
<div class="row">
  <div id="item-search" class="col s2 right">
    <%= render partial: "partials/search_without_title" %>
  </div>
</div>
<% end %>
<% if logged_in? && current_user.role?(:admin) %>
  <%= render partial: "tabbed_items" %>
<% else %>
  <%= render partial: "item_grid", locals: {items: @breads,
                                                      item_type: 'breads'} %>

  <%= render partial: "item_grid", locals: {items: @muffins,
                                                      item_type: 'muffins'} %>

  <%= render partial: "item_grid", locals: {items: @pastries,
                                                      item_type: 'pastries'} %>
<% end %>

<% if can? :create, Item %>
  <%= render partial: "partials/add_new_object", locals: {model_name: 'item'} %>
<% end %>

<% if !logged_in? %>
  <div  align="center">
    <%= link_to "Not a customer? Create an account here!", new_customer_path, class: "waves-effect waves-lignt btn" %>
  </div>
<% end %>

app/views/items/new.html.erb
<%= render partial: "partials/form_structure", locals: {object: @item, 
                                                        type_of_form: "Create a New Item",
                                                        fields: "fields"} %>

app/views/items/show.html.erb
<% if logged_in? && current_user.role?(:admin) %>
  <%= render partial: "partials/structure1", locals: {primary: "item_details", 
                                                    secondary: nil, sidebar: "partials/price_history" }%>

<% else %>
  <%= render partial: "partials/structure1", locals: {primary: "item_details", 
                                                    secondary: nil, sidebar: "partials/similar_items" }%>

<% end %>

<!-- Add buttons to list all, edit project or destroy object -->
<%= render partial: "partials/object_options", locals: {model_name: "item", object: @item}  %>